[tools]
node = "24"
pnpm = "10"

[tasks.install]
run = "pnpm install"

[tasks.dev]
depends  = ["install"]
run = "pnpm run docs:dev"

[tasks.build]
depends  = ["install"]
run = "pnpm run docs:build"

[tasks.preview]
depends  = ["build"]
run = "pnpm run docs:preview"

