# 开发工具
[tools]
node = "24"
pnpm = "10"

# 项目任务
[tasks.install]
description = "安装依赖"
run = "pnpm install"

[tasks.build]
description = "构建"
depends  = ["install"]
run = "pnpm run docs:build"

[tasks.dev]
description = "开发"
depends  = ["install"]
run = "pnpm run docs:dev"

[tasks.preview]
description = "预览"
depends  = ["build"]
run = "pnpm run docs:preview"

